version: '3.8'

services:
    dev:
        container_name: api_dev
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: yarn start:debug
        ports:
            - 3000:3000
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: api_prod
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: yarn start:prod
        ports:
            - 80:3000
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    nesjs-network: