name: Deploy
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: 'https://knowledge-rating-api.herokuapp.com/health'
          checkstring: "ok"
          usedocker: true
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HD_MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          HD_PORT: ${{ secrets.PORT }}